
// Medical Conditions - Using Dr Green API exact enum values
// Values match Dr Green exactly, Labels are user-friendly
export const MEDICAL_CONDITIONS = [
  { value: 'adhd', label: 'ADHD' },
  { value: 'agoraphobia', label: 'Agoraphobia' },
  { value: 'anxiety', label: 'Anxiety' },
  { value: 'appetite_disorders', label: 'Appetite Disorders' },
  { value: 'arthritis', label: 'Arthritis' },
  { value: 'autistic_spectrum_disorder', label: 'Autistic Spectrum Disorder' },
  { value: 'back_and_neck_pain', label: 'Back and Neck Pain' },
  { value: 'bipolar', label: 'Bipolar Disorder' },
  { value: 'bladder_pain', label: 'Bladder Pain' },
  { value: 'cancer_pain_and_nausea', label: 'Cancer Pain and Nausea' },
  { value: 'chrohns_disease_or_colitis_pain', label: "Crohn's Disease or Colitis Pain" },
  { value: 'chronic_and_long_term_pain', label: 'Chronic and Long-term Pain' },
  { value: 'chronic_fatigue_syndrome', label: 'Chronic Fatigue Syndrome' },
  { value: 'cluster_headaches', label: 'Cluster Headaches' },
  { value: 'complex_regional_pain_syndrome', label: 'Complex Regional Pain Syndrome' },
  { value: 'depression', label: 'Depression' },
  { value: 'dermatology', label: 'Dermatology Conditions' },
  { value: 'dvt', label: 'DVT (Deep Vein Thrombosis)' },
  { value: 'ehlers-danlos_syndrome', label: 'Ehlers-Danlos Syndrome' },
  { value: 'endometriosis', label: 'Endometriosis' },
  { value: 'epilepsy', label: 'Epilepsy' },
  { value: 'female_gynaecological_pain', label: 'Female Gynaecological Pain' },
  { value: 'fibromyalgia', label: 'Fibromyalgia' },
  { value: 'irritable_bowel_syndrome', label: 'Irritable Bowel Syndrome (IBS)' },
  { value: 'migraine', label: 'Migraine' },
  { value: 'multiple_sclerosis_pain_and_muscle_spasm', label: 'Multiple Sclerosis Pain and Muscle Spasm' },
  { value: 'nerve_pain', label: 'Nerve Pain' },
  { value: 'ocd', label: 'OCD (Obsessive-Compulsive Disorder)' },
  { value: 'osteoporosis', label: 'Osteoporosis' },
  { value: 'parkinsons_disease', label: "Parkinson's Disease" },
  { value: 'personality_disorder', label: 'Personality Disorder' },
  { value: 'phantom_limb_pain', label: 'Phantom Limb Pain' },
  { value: 'post_traumatic_stress_disorder', label: 'PTSD (Post-Traumatic Stress Disorder)' },
  { value: 'sciatica', label: 'Sciatica' },
  { value: 'scoliosis', label: 'Scoliosis' },
  { value: 'sleep_disorders', label: 'Sleep Disorders' },
  { value: 'spondylolisthesis', label: 'Spondylolisthesis' },
  { value: 'thalassemia_major_blood_disorder', label: 'Thalassemia Major Blood Disorder' },
  { value: 'the_menopause', label: 'The Menopause' },
  { value: 'tinnitus', label: 'Tinnitus' },
  { value: 'tourette_syndrome', label: 'Tourette Syndrome' },
  { value: 'trigeminal_neuralgia', label: 'Trigeminal Neuralgia' },
  // Extras not in Dr Green enum - will map to other_medical_condition
  { value: 'asthma', label: 'Asthma' },
  { value: 'glaucoma', label: 'Glaucoma' },
  { value: 'lupus', label: 'Lupus' },
  { value: 'other_medical_condition', label: 'Other Medical Condition' },
] as const;

// Prescribed Medications from Dr. Green API
export const PRESCRIBED_MEDICATIONS = [
  { value: 'alprazolam', label: 'Alprazolam' },
  { value: 'alentanil', label: 'Alentanil' },
  { value: 'amitryptyline', label: 'Amitriptyline' },
  { value: 'atomoxetine', label: 'Atomoxetine' },
  { value: 'azathioprine', label: 'Azathioprine' },
  { value: 'baclofen', label: 'Baclofen' },
  { value: 'bupropion', label: 'Bupropion' },
  { value: 'citalopram', label: 'Citalopram' },
  { value: 'clonazepam', label: 'Clonazepam' },
  { value: 'codeine', label: 'Codeine' },
  { value: 'codeine_phosphate', label: 'Codeine Phosphate' },
  { value: 'co-codamol_30-500', label: 'Co-codamol 30/500' },
  { value: 'dexamfetamine', label: 'Dexamfetamine' },
  { value: 'diazepam', label: 'Diazepam' },
  { value: 'diclofenac', label: 'Diclofenac' },
  { value: 'dihydrocodeine', label: 'Dihydrocodeine' },
  { value: 'fentanyl', label: 'Fentanyl' },
  { value: 'fluoxetine', label: 'Fluoxetine' },
  { value: 'folic_acid_and_prozac', label: 'Folic Acid and Prozac' },
  { value: 'gabapentin', label: 'Gabapentin' },
  { value: 'guanfacine', label: 'Guanfacine' },
  { value: 'infliximab', label: 'Infliximab' },
  { value: 'leflunomide', label: 'Leflunomide' },
  { value: 'lithium', label: 'Lithium' },
  { value: 'lorazepam', label: 'Lorazepam' },
  { value: 'methadone', label: 'Methadone' },
  { value: 'methotrexate', label: 'Methotrexate' },
  { value: 'methylphenidate', label: 'Methylphenidate' },
  { value: 'mirtazapine', label: 'Mirtazapine' },
  { value: 'morphine', label: 'Morphine' },
  { value: 'naproxen', label: 'Naproxen' },
  { value: 'oxycodone', label: 'Oxycodone' },
  { value: 'paroxetine', label: 'Paroxetine' },
  { value: 'pregabalin', label: 'Pregabalin' },
  { value: 'propranolol', label: 'Propranolol' },
  { value: 'sertraline', label: 'Sertraline' },
  { value: 'temazepam', label: 'Temazepam' },
  { value: 'tramadol', label: 'Tramadol' },
  { value: 'venlafaxine', label: 'Venlafaxine' },
  { value: 'vyvanse', label: 'Vyvanse' },
  { value: 'zopiclone', label: 'Zopiclone' },
  { value: 'none', label: 'None' },
] as const;

// Country codes with phone codes
export const COUNTRY_CODES = [
  { code: 'GB', label: 'United Kingdom', phoneCode: '+44' },
  { code: 'US', label: 'United States', phoneCode: '+1' },
  { code: 'PT', label: 'Portugal', phoneCode: '+351' },
  { code: 'ES', label: 'Spain', phoneCode: '+34' },
  { code: 'FR', label: 'France', phoneCode: '+33' },
  { code: 'DE', label: 'Germany', phoneCode: '+49' },
  { code: 'IT', label: 'Italy', phoneCode: '+39' },
  { code: 'NL', label: 'Netherlands', phoneCode: '+31' },
  { code: 'BE', label: 'Belgium', phoneCode: '+32' },
  { code: 'AT', label: 'Austria', phoneCode: '+43' },
  { code: 'IE', label: 'Ireland', phoneCode: '+353' },
  { code: 'CA', label: 'Canada', phoneCode: '+1' },
  { code: 'AU', label: 'Australia', phoneCode: '+61' },
  { code: 'NZ', label: 'New Zealand', phoneCode: '+64' },
] as const;

// Cannabis frequency options
export const CANNABIS_FREQUENCY_OPTIONS = [
  { value: 'everyday', label: 'Everyday' },
  { value: 'every_other_day', label: 'Every other day' },
  { value: '1-2_times_per_week', label: '1-2 times per week' },
  { value: 'never', label: 'Never' },
] as const;

// Business types
export const BUSINESS_TYPES = [
  { value: 'manufacturer', label: 'Manufacturer' },
  { value: 'distributor', label: 'Distributor' },
  { value: 'retailer', label: 'Retailer' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'other', label: 'Other' },
] as const;
