
// Medical Conditions from Dr. Green API
export const MEDICAL_CONDITIONS = [
  { value: 'adhd', label: 'ADHD' },
  { value: 'agoraphobia', label: 'Agoraphobia' },
  { value: 'anxiety', label: 'Anxiety' },
  { value: 'appetite_disorders', label: 'Appetite Disorders' },
  { value: 'arthritis', label: 'Arthritis' },
  { value: 'asthma', label: 'Asthma' },
  { value: 'autism', label: 'Autism' },
  { value: 'bipolar_disorder', label: 'Bipolar Disorder' },
  { value: 'bowel_disease', label: 'Bowel Disease' },
  { value: 'cancer', label: 'Cancer' },
  { value: 'chronic_pain', label: 'Chronic Pain' },
  { value: 'crohns_disease', label: "Crohn's Disease" },
  { value: 'depression', label: 'Depression' },
  { value: 'dystonia', label: 'Dystonia' },
  { value: 'endometriosis', label: 'Endometriosis' },
  { value: 'epilepsy', label: 'Epilepsy' },
  { value: 'fibromyalgia', label: 'Fibromyalgia' },
  { value: 'glaucoma', label: 'Glaucoma' },
  { value: 'headaches', label: 'Headaches' },
  { value: 'insomnia', label: 'Insomnia' },
  { value: 'ibs', label: 'IBS (Irritable Bowel Syndrome)' },
  { value: 'lupus', label: 'Lupus' },
  { value: 'migraines', label: 'Migraines' },
  { value: 'ms', label: 'Multiple Sclerosis (MS)' },
  { value: 'muscle_spasms', label: 'Muscle Spasms' },
  { value: 'nausea', label: 'Nausea' },
  { value: 'ocd', label: 'OCD (Obsessive-Compulsive Disorder)' },
  { value: 'parkinsons', label: "Parkinson's Disease" },
  { value: 'ptsd', label: 'PTSD (Post-Traumatic Stress Disorder)' },
  { value: 'rheumatoid_arthritis', label: 'Rheumatoid Arthritis' },
  { value: 'scoliosis', label: 'Scoliosis' },
  { value: 'seizures', label: 'Seizures' },
  { value: 'stress', label: 'Stress' },
  { value: 'tourettes', label: 'Tourette Syndrome' },
  { value: 'ulcerative_colitis', label: 'Ulcerative Colitis' },
  { value: 'other', label: 'Other' },
] as const;

// Prescribed Medications from Dr. Green API
export const PRESCRIBED_MEDICATIONS = [
  { value: 'alprazolam', label: 'Alprazolam' },
  { value: 'alentanil', label: 'Alentanil' },
  { value: 'amitryptyline', label: 'Amitriptyline' },
  { value: 'atomoxetine', label: 'Atomoxetine' },
  { value: 'azathioprine', label: 'Azathioprine' },
  { value: 'baclofen', label: 'Baclofen' },
  { value: 'bupropion', label: 'Bupropion' },
  { value: 'citalopram', label: 'Citalopram' },
  { value: 'clonazepam', label: 'Clonazepam' },
  { value: 'codeine', label: 'Codeine' },
  { value: 'codeine_phosphate', label: 'Codeine Phosphate' },
  { value: 'co-codamol_30-500', label: 'Co-codamol 30/500' },
  { value: 'dexamfetamine', label: 'Dexamfetamine' },
  { value: 'diazepam', label: 'Diazepam' },
  { value: 'diclofenac', label: 'Diclofenac' },
  { value: 'dihydrocodeine', label: 'Dihydrocodeine' },
  { value: 'fentanyl', label: 'Fentanyl' },
  { value: 'fluoxetine', label: 'Fluoxetine' },
  { value: 'folic_acid_and_prozac', label: 'Folic Acid and Prozac' },
  { value: 'gabapentin', label: 'Gabapentin' },
  { value: 'guanfacine', label: 'Guanfacine' },
  { value: 'infliximab', label: 'Infliximab' },
  { value: 'leflunomide', label: 'Leflunomide' },
  { value: 'lithium', label: 'Lithium' },
  { value: 'lorazepam', label: 'Lorazepam' },
  { value: 'methadone', label: 'Methadone' },
  { value: 'methotrexate', label: 'Methotrexate' },
  { value: 'methylphenidate', label: 'Methylphenidate' },
  { value: 'mirtazapine', label: 'Mirtazapine' },
  { value: 'morphine', label: 'Morphine' },
  { value: 'naproxen', label: 'Naproxen' },
  { value: 'oxycodone', label: 'Oxycodone' },
  { value: 'paroxetine', label: 'Paroxetine' },
  { value: 'pregabalin', label: 'Pregabalin' },
  { value: 'propranolol', label: 'Propranolol' },
  { value: 'sertraline', label: 'Sertraline' },
  { value: 'temazepam', label: 'Temazepam' },
  { value: 'tramadol', label: 'Tramadol' },
  { value: 'venlafaxine', label: 'Venlafaxine' },
  { value: 'vyvanse', label: 'Vyvanse' },
  { value: 'zopiclone', label: 'Zopiclone' },
  { value: 'none', label: 'None' },
] as const;

// Country codes with phone codes
export const COUNTRY_CODES = [
  { code: 'GB', label: 'United Kingdom', phoneCode: '+44' },
  { code: 'US', label: 'United States', phoneCode: '+1' },
  { code: 'PT', label: 'Portugal', phoneCode: '+351' },
  { code: 'ES', label: 'Spain', phoneCode: '+34' },
  { code: 'FR', label: 'France', phoneCode: '+33' },
  { code: 'DE', label: 'Germany', phoneCode: '+49' },
  { code: 'IT', label: 'Italy', phoneCode: '+39' },
  { code: 'NL', label: 'Netherlands', phoneCode: '+31' },
  { code: 'BE', label: 'Belgium', phoneCode: '+32' },
  { code: 'AT', label: 'Austria', phoneCode: '+43' },
  { code: 'IE', label: 'Ireland', phoneCode: '+353' },
  { code: 'CA', label: 'Canada', phoneCode: '+1' },
  { code: 'AU', label: 'Australia', phoneCode: '+61' },
  { code: 'NZ', label: 'New Zealand', phoneCode: '+64' },
] as const;

// Cannabis frequency options
export const CANNABIS_FREQUENCY_OPTIONS = [
  { value: 'everyday', label: 'Everyday' },
  { value: 'every_other_day', label: 'Every other day' },
  { value: '1-2_times_per_week', label: '1-2 times per week' },
  { value: 'never', label: 'Never' },
] as const;

// Business types
export const BUSINESS_TYPES = [
  { value: 'manufacturer', label: 'Manufacturer' },
  { value: 'distributor', label: 'Distributor' },
  { value: 'retailer', label: 'Retailer' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'other', label: 'Other' },
] as const;
